# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: IgorPavlov.7-Zip
PackageVersion: "23.01"
PackageLocale: en-US
Publisher: Igor Pavlov
PackageName: 7-Zip
License: MIT License
Copyright: Copyright (c) 1999-2023 Igor Pavlov
ShortDescription: 7-Zip Installer
ManifestType: defaultLocale
ManifestVersion: 1.5.0
