# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: IgorPavlov.7-Zip
PackageVersion: "23.01"
InstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://www.7-zip.org/a/7z2301-x64.exe
  InstallerSha256: 26CB6E9F56333682122FAFE79DBCDFD51E9F47CC7217DCCD29AC6FC33B5598CD
ManifestType: installer
ManifestVersion: 1.5.0
